'use client';

import React, { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText,
  Download,
  Eye,
  Code,
  ChevronDown,
  Check,
  Copy,
  Palette,
  FileType,
  Sparkles,
} from 'lucide-react';

import { cn } from '@/lib/utils';

// Template options
const templates = [
  { id: 'proposal', name: 'Project Proposal', icon: FileText },
  { id: 'contract', name: 'Service Contract', icon: FileType },
  { id: 'report', name: 'Status Report', icon: FileText },
  { id: 'invoice', name: 'Invoice', icon: FileText },
];

// Style presets
const styles = [
  { id: 'professional', name: 'Professional', color: '#06b6d4' },
  { id: 'minimal', name: 'Minimal', color: '#64748b' },
  { id: 'modern', name: 'Modern', color: '#10b981' },
];

// Sample variables for interpolation
const sampleVariables = {
  clientName: 'Acme Corporation',
  projectName: 'Website Redesign',
  date: new Date().toLocaleDateString(),
  amount: '$15,000',
  consultant: 'Tech Integration Labs',
};

// Sample markdown content
const getTemplateContent = (templateId: string) => {
  const templates: Record<string, string> = {
    proposal: `# Project Proposal

## {{projectName}}

**Prepared for:** {{clientName}}
**Date:** {{date}}
**Prepared by:** {{consultant}}

---

## Executive Summary

This proposal outlines our approach to delivering a comprehensive solution for {{clientName}}'s {{projectName}} initiative.

## Scope of Work

1. **Discovery & Planning**
   - Requirements gathering
   - Technical architecture
   - Timeline development

2. **Design & Development**
   - UI/UX design
   - Frontend implementation
   - Backend integration

3. **Testing & Launch**
   - Quality assurance
   - Performance optimization
   - Deployment & training

## Investment

**Total Project Cost:** {{amount}}

Payment terms: 50% upfront, 50% on completion.

---

*{{consultant}} | Building the Future*`,

    contract: `# Service Agreement

**Between:** {{consultant}} ("Provider")
**And:** {{clientName}} ("Client")
**Effective Date:** {{date}}

---

## 1. Services

Provider agrees to deliver {{projectName}} services as outlined in the attached Statement of Work.

## 2. Compensation

Client agrees to pay Provider {{amount}} for the services described herein.

## 3. Term

This agreement shall commence on {{date}} and continue until project completion.

## 4. Confidentiality

Both parties agree to maintain confidentiality of all proprietary information.

---

**Agreed and Accepted:**

_________________________
{{clientName}}

_________________________
{{consultant}}`,

    report: `# Status Report

## {{projectName}}

**Client:** {{clientName}}
**Report Date:** {{date}}
**Prepared by:** {{consultant}}

---

## Summary

This week we made significant progress on the {{projectName}} initiative.

## Completed This Week

- [x] Initial design mockups approved
- [x] Database schema finalized
- [x] Authentication system implemented
- [x] API endpoints for core features

## In Progress

- [ ] Frontend component development
- [ ] Integration testing
- [ ] Documentation

## Blockers

None at this time.

## Next Steps

1. Complete remaining frontend components
2. Begin user acceptance testing
3. Prepare deployment documentation

---

*Report generated by {{consultant}}*`,

    invoice: `# Invoice

**From:** {{consultant}}
**To:** {{clientName}}
**Date:** {{date}}
**Invoice #:** INV-2024-001

---

## Services Rendered

| Description | Amount |
|-------------|--------|
| {{projectName}} - Phase 1 | {{amount}} |

---

**Subtotal:** {{amount}}
**Tax (0%):** $0.00
**Total Due:** {{amount}}

---

## Payment Details

Please remit payment within 30 days to:

**Bank:** Example Bank
**Account:** XXXX-XXXX-1234

---

*Thank you for your business!*
*{{consultant}}*`,
  };

  return templates[templateId] || templates.proposal;
};

// Interpolate variables in content
const interpolateContent = (content: string, variables: Record<string, string>) => {
  let result = content;
  Object.entries(variables).forEach(([key, value]) => {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
  });
  return result;
};

// Simple markdown to HTML converter
const markdownToHtml = (markdown: string) => {
  let html = markdown
    // Headers
    .replace(/^### (.*$)/gim, '<h3 class="text-lg font-semibold text-white mt-4 mb-2">$1</h3>')
    .replace(/^## (.*$)/gim, '<h2 class="text-xl font-bold text-white mt-6 mb-3">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 class="text-2xl font-bold text-white mb-4">$1</h1>')
    // Bold and italic
    .replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.*?)\*\*/g, '<strong class="text-white">$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    // Horizontal rules
    .replace(/^---$/gim, '<hr class="border-white/10 my-4" />')
    // Checkboxes
    .replace(/- \[x\] (.*$)/gim, '<div class="flex items-center gap-2 text-emerald-400"><span>✓</span> $1</div>')
    .replace(/- \[ \] (.*$)/gim, '<div class="flex items-center gap-2 text-white/60"><span>○</span> $1</div>')
    // List items
    .replace(/^\d+\. (.*$)/gim, '<li class="ml-4 text-white/80">$1</li>')
    .replace(/^- (.*$)/gim, '<li class="ml-4 text-white/80">• $1</li>')
    // Tables (simple)
    .replace(/\| (.*) \| (.*) \|/g, '<div class="flex justify-between py-1 border-b border-white/10"><span>$1</span><span>$2</span></div>')
    // Line breaks
    .replace(/\n\n/g, '</p><p class="text-white/70 mb-3">')
    .replace(/\n/g, '<br />');

  return `<div class="prose prose-invert max-w-none"><p class="text-white/70 mb-3">${html}</p></div>`;
};

export function DocumentGenerator() {
  const [selectedTemplate, setSelectedTemplate] = useState('proposal');
  const [selectedStyle, setSelectedStyle] = useState('professional');
  const [showTemplateDropdown, setShowTemplateDropdown] = useState(false);
  const [viewMode, setViewMode] = useState<'split' | 'preview' | 'code'>('split');
  const [variables, setVariables] = useState(sampleVariables);
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const rawContent = getTemplateContent(selectedTemplate);
  const interpolatedContent = interpolateContent(rawContent, variables);
  const htmlPreview = markdownToHtml(interpolatedContent);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(interpolatedContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [interpolatedContent]);

  const handleDownload = useCallback(() => {
    setIsGenerating(true);

    // Simulate PDF generation
    setTimeout(() => {
      const blob = new Blob([interpolatedContent], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${selectedTemplate}-${Date.now()}.md`;
      a.click();
      URL.revokeObjectURL(url);
      setIsGenerating(false);
    }, 1500);
  }, [interpolatedContent, selectedTemplate]);

  const currentStyle = styles.find(s => s.id === selectedStyle);

  return (
    <div className="rounded-2xl border border-white/10 bg-surface/50 overflow-hidden">
      {/* Toolbar */}
      <div className="flex items-center justify-between p-4 border-b border-white/10 bg-white/[0.02]">
        <div className="flex items-center gap-3">
          {/* Template Selector */}
          <div className="relative">
            <button
              onClick={() => setShowTemplateDropdown(!showTemplateDropdown)}
              className="flex items-center gap-2 px-3 py-2 rounded-lg bg-white/5 hover:bg-white/10 transition-colors text-white text-sm"
            >
              <FileText className="w-4 h-4 text-cyan-400" />
              {templates.find(t => t.id === selectedTemplate)?.name}
              <ChevronDown className={cn(
                'w-4 h-4 transition-transform',
                showTemplateDropdown && 'rotate-180'
              )} />
            </button>

            <AnimatePresence>
              {showTemplateDropdown && (
                <motion.div
                  initial={{ opacity: 0, y: -8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  className="absolute top-full left-0 mt-2 w-48 rounded-lg border border-white/10 bg-surface overflow-hidden z-20"
                >
                  {templates.map(template => (
                    <button
                      key={template.id}
                      onClick={() => {
                        setSelectedTemplate(template.id);
                        setShowTemplateDropdown(false);
                      }}
                      className={cn(
                        'w-full flex items-center gap-2 px-3 py-2 text-sm transition-colors',
                        selectedTemplate === template.id
                          ? 'bg-cyan-500/20 text-cyan-400'
                          : 'text-white/70 hover:bg-white/5'
                      )}
                    >
                      <template.icon className="w-4 h-4" />
                      {template.name}
                      {selectedTemplate === template.id && (
                        <Check className="w-4 h-4 ml-auto" />
                      )}
                    </button>
                  ))}
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Style Selector */}
          <div className="flex items-center gap-1 p-1 bg-white/5 rounded-lg">
            {styles.map(style => (
              <button
                key={style.id}
                onClick={() => setSelectedStyle(style.id)}
                className={cn(
                  'flex items-center gap-1.5 px-2 py-1 rounded text-xs transition-colors',
                  selectedStyle === style.id
                    ? 'bg-white/10 text-white'
                    : 'text-white/40 hover:text-white/60'
                )}
              >
                <div
                  className="w-3 h-3 rounded-full"
                  style={{ backgroundColor: style.color }}
                />
                {style.name}
              </button>
            ))}
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* View Mode Toggle */}
          <div className="flex items-center gap-1 p-1 bg-white/5 rounded-lg">
            <button
              onClick={() => setViewMode('split')}
              className={cn(
                'p-1.5 rounded transition-colors',
                viewMode === 'split' ? 'bg-white/10 text-white' : 'text-white/40'
              )}
              title="Split View"
            >
              <div className="flex gap-0.5">
                <div className="w-2 h-4 border border-current rounded-sm" />
                <div className="w-2 h-4 border border-current rounded-sm" />
              </div>
            </button>
            <button
              onClick={() => setViewMode('code')}
              className={cn(
                'p-1.5 rounded transition-colors',
                viewMode === 'code' ? 'bg-white/10 text-white' : 'text-white/40'
              )}
              title="Code View"
            >
              <Code className="w-4 h-4" />
            </button>
            <button
              onClick={() => setViewMode('preview')}
              className={cn(
                'p-1.5 rounded transition-colors',
                viewMode === 'preview' ? 'bg-white/10 text-white' : 'text-white/40'
              )}
              title="Preview"
            >
              <Eye className="w-4 h-4" />
            </button>
          </div>

          {/* Actions */}
          <button
            onClick={handleCopy}
            className="p-2 rounded-lg bg-white/5 hover:bg-white/10 transition-colors text-white/60 hover:text-white"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
          </button>

          <button
            onClick={handleDownload}
            disabled={isGenerating}
            className={cn(
              'flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-all',
              isGenerating
                ? 'bg-cyan-500/20 text-cyan-400'
                : 'bg-cyan-500 hover:bg-cyan-600 text-white'
            )}
          >
            {isGenerating ? (
              <>
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                >
                  <Sparkles className="w-4 h-4" />
                </motion.div>
                Generating...
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                Export
              </>
            )}
          </button>
        </div>
      </div>

      {/* Editor Area */}
      <div className={cn(
        'grid gap-0',
        viewMode === 'split' ? 'grid-cols-2' : 'grid-cols-1'
      )}>
        {/* Code/Markdown Panel */}
        {(viewMode === 'split' || viewMode === 'code') && (
          <div className="border-r border-white/10">
            <div className="flex items-center justify-between px-4 py-2 bg-white/[0.02] border-b border-white/10">
              <span className="text-xs text-white/40 font-mono">markdown</span>
              <Palette className="w-3 h-3 text-white/20" />
            </div>
            <div className="h-[400px] overflow-auto">
              <pre className="p-4 text-sm font-mono text-white/70 whitespace-pre-wrap">
                {interpolatedContent}
              </pre>
            </div>
          </div>
        )}

        {/* Preview Panel */}
        {(viewMode === 'split' || viewMode === 'preview') && (
          <div
            className="relative"
            style={{
              '--accent-color': currentStyle?.color || '#06b6d4',
            } as React.CSSProperties}
          >
            <div className="flex items-center justify-between px-4 py-2 bg-white/[0.02] border-b border-white/10">
              <span className="text-xs text-white/40">Preview</span>
              <Eye className="w-3 h-3 text-white/20" />
            </div>
            <div className="h-[400px] overflow-auto p-6 bg-gradient-to-br from-white/[0.02] to-transparent">
              {/* Decorative accent bar */}
              <div
                className="absolute top-[45px] left-0 w-1 h-[calc(100%-45px)]"
                style={{ backgroundColor: currentStyle?.color }}
              />

              <div
                dangerouslySetInnerHTML={{ __html: htmlPreview }}
                className="pl-4"
              />
            </div>
          </div>
        )}
      </div>

      {/* Variables Editor */}
      <div className="p-4 border-t border-white/10 bg-white/[0.02]">
        <div className="flex items-center gap-2 mb-3">
          <Sparkles className="w-4 h-4 text-amber-400" />
          <span className="text-sm font-medium text-white">Template Variables</span>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          {Object.entries(variables).map(([key, value]) => (
            <div key={key} className="space-y-1">
              <label className="text-xs text-white/40 font-mono">{`{{${key}}}`}</label>
              <input
                type="text"
                value={value}
                onChange={(e) => setVariables(prev => ({ ...prev, [key]: e.target.value }))}
                className="w-full px-2 py-1 rounded bg-white/5 border border-white/10 text-sm text-white placeholder-white/30 focus:outline-none focus:border-cyan-500/50"
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default DocumentGenerator;
